name: Main pipeline

on: [push, pull_request]

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
      - name: Run ShellCheck
        run: |
          shellcheck scripts/*.sh

      - name: Run gofmt
        run: |
          ./scripts/checks.sh
  test:
    strategy:
      matrix:
        go-version: [1.17.x, 1.18.x, 1.x]
        platform: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: verify
        run: make verify

      - name: ensure compilation
        env:
          GOOS: linux
        run: go build

      - name: Use Docker
        uses: actions-hub/docker/cli@master
        if: ${{ matrix.platform == 'ubuntu-latest' }}
        env:
          SKIP_LOGIN: true

      - name: test nested in container
        run: make test-unit-nested
        if: ${{ matrix.platform == 'ubuntu-latest' }}

      - name: gotestsum
        # only run tests on linux, there are a number of things that won't allow the tests to run on anything else
        # many (maybe, all?) images used can only be build on Linux, they don't have Windows in their manifest, and
        # we can't put Windows Server in "Linux Mode" in Github actions
        # another, host mode is only available on Linux, and we have tests around that, do we skip them?
        if: ${{ matrix.platform == 'ubuntu-latest' }}
        run: make test-unit

      - name: merge coverage-results
        if: ${{ matrix.platform == 'ubuntu-latest' }}
        run: |
          sudo chown $(whoami) nested-cover.txt && \
          go run github.com/wadey/gocovmerge@latest nested-cover.txt cover.txt > cover-all.txt

        # only report code coverage on linux
      - name: Upload coverage report
        if: ${{ matrix.platform == 'ubuntu-latest' }}
        uses: codecov/codecov-action@v2
        with:
          files: ./cover-all.txt
          name: testcontainers-go-${{ matrix.go-version }}

      - name: modTidy e2e tests
        if: ${{ matrix.platform == 'ubuntu-latest' }}
        run: make -C e2e tools-tidy

      - name: Run e2e tests
        if: ${{ matrix.platform == 'ubuntu-latest' }}
        run: make test-e2e

      - name: Run checker
        run: |
          ./scripts/check_environment.sh

      - name: Test Summary
        uses: test-summary/action@v1
        with:
          paths: "**/TEST-*.xml"
        if: always()
